CREATE TABLE IF NOT EXISTS scolia_config (
    user_id INT UNSIGNED NOT NULL PRIMARY KEY,
    serial_number VARCHAR(191) NOT NULL DEFAULT '',
    api_token VARCHAR(191) NOT NULL DEFAULT '',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_scolia_config_user FOREIGN KEY (user_id) REFERENCES oauth_users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
