CREATE TABLE IF NOT EXISTS darts501_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    owner_user_id INT UNSIGNED NOT NULL,
    save_name VARCHAR(160) NOT NULL DEFAULT '501 Darts',
    participant_summary VARCHAR(1000) NOT NULL DEFAULT '',
    participants_json JSON NOT NULL,
    state_json JSON NOT NULL,
    participant_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    event_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_event_at DATETIME(3) NULL DEFAULT NULL,
    is_archived TINYINT(1) NOT NULL DEFAULT 0,
    archived_at DATETIME(3) NULL DEFAULT NULL,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL DEFAULT NULL,
    CONSTRAINT fk_darts501_sessions_owner FOREIGN KEY (owner_user_id) REFERENCES portal_users (id),
    INDEX idx_darts501_sessions_owner_active_updated (owner_user_id, is_deleted, updated_at),
    INDEX idx_darts501_sessions_last_event (last_event_at),
    INDEX idx_darts501_sessions_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS darts501_session_participants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT UNSIGNED NOT NULL,
    seat_no INT UNSIGNED NOT NULL,
    portal_user_id INT UNSIGNED NULL,
    invited_by_user_id INT UNSIGNED NULL,
    display_name VARCHAR(120) NOT NULL DEFAULT '',
    participant_role ENUM('owner', 'friend', 'guest') NOT NULL DEFAULT 'guest',
    invitation_status ENUM('accepted', 'pending', 'declined', 'removed') NOT NULL DEFAULT 'accepted',
    current_remaining_score INT UNSIGNED NOT NULL DEFAULT 501,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    joined_at DATETIME(3) NULL DEFAULT NULL,
    last_throw_at DATETIME(3) NULL DEFAULT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_darts501_participants_session FOREIGN KEY (session_id) REFERENCES darts501_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_darts501_participants_user FOREIGN KEY (portal_user_id) REFERENCES portal_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_darts501_participants_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES portal_users (id) ON DELETE SET NULL,
    CONSTRAINT uq_darts501_participants_seat UNIQUE (session_id, seat_no),
    INDEX idx_darts501_participants_user_active (portal_user_id, invitation_status, is_active),
    INDEX idx_darts501_participants_session_status (session_id, invitation_status, is_active),
    INDEX idx_darts501_participants_last_throw (last_throw_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS darts501_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT UNSIGNED NOT NULL,
    participant_id BIGINT UNSIGNED NULL,
    player_user_id INT UNSIGNED NULL,
    recorded_by_user_id INT UNSIGNED NULL,
    event_no INT UNSIGNED NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    event_source VARCHAR(32) NOT NULL DEFAULT '',
    player_index INT UNSIGNED NULL,
    player_name VARCHAR(120) NOT NULL DEFAULT '',
    throw_label VARCHAR(20) NOT NULL DEFAULT '',
    sector_result VARCHAR(32) NOT NULL DEFAULT '',
    score_delta INT NOT NULL DEFAULT 0,
    remaining_after INT UNSIGNED NOT NULL DEFAULT 501,
    detected_at DATETIME(3) NULL DEFAULT NULL,
    payload_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_darts501_events_session FOREIGN KEY (session_id) REFERENCES darts501_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_darts501_events_participant FOREIGN KEY (participant_id) REFERENCES darts501_session_participants (id) ON DELETE SET NULL,
    CONSTRAINT fk_darts501_events_player_user FOREIGN KEY (player_user_id) REFERENCES portal_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_darts501_events_recorded_by FOREIGN KEY (recorded_by_user_id) REFERENCES portal_users (id) ON DELETE SET NULL,
    CONSTRAINT uq_darts501_session_event UNIQUE (session_id, event_no),
    INDEX idx_darts501_events_session_event (session_id, event_no),
    INDEX idx_darts501_events_player_detected (player_user_id, detected_at),
    INDEX idx_darts501_events_recorded_by (recorded_by_user_id, created_at),
    INDEX idx_darts501_events_detected (detected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;